CREATE DATABASE IF NOT EXISTS idsBench;
USE idsBench;

CREATE TABLE IF NOT EXISTS brokerMessage(
    id INT AUTO_INCREMENT PRIMARY KEY, 
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    temperature DECIMAL(3,1),
    capacity INT,
    message VARCHAR(50)
);
